### ISSUE TITLE
Very cool!

### ISSUE THREAD

**Issue by lodenrogue** [leefogg/Gameboy-Example-Collection#1]
Very cool project! In Assembly?!?! That's awesome! What are some reasons you chose assembly over another language?

**Comment by leefogg** [comment]
Hey! Thanks for noticing! That's a simple answer really, Currently you can only develop for the GB in C and assembly and the best documented C compiler is known to have loads of bugs, that matched with not able to debug it when its running was a big no-no. Many of these effects need cycle accurate timings too.

**Comment by lodenrogue** [comment]
Oh gotcha! Is there a large community wanting these retro games? I wonder if there's demand for a modern library written in python, etc.

**Comment by leefogg** [comment]
I don't think there's any demand for GB games but it's a refreshing change from modern-day high level programming where we spend so much time thinking about deployment, libraries, compatibility etc that it's nice to have nothing but the instructions. We do have a discord channel for the GB Dev community and we're always looking for tools to make Dev easier and more fun..

**Comment by lodenrogue** [comment]
Can you share the channel info? I'd love to pop in and check it out

**Comment by leefogg** [comment]
There a link to the discord on our main project
https://github.com/gbdev/pandocs
